### ISSUE TITLE
GSA and GSA-Grasshopper issues

### ISSUE THREAD

**Issue by netsonicyxf** [arup-group/GSA-Grasshopper#131]
1. GSA 10.1.60.42 and GSA-Grasshopper addon 0.9.19~0.9.21 crash Rhino v7 R21.

2. With GSA 10.1.59.30 and GSA-Grasshopper addon 0.9.17, when loading grasshopper, it shows error:

Object: GlobalResult (level 1)
{
  Exception has been thrown by the target of an invocation.
  TargetInvocationException
}

Object: GlobalResult (level 2)
{
  The type initializer for 'Oasys.Units.Moment' threw an exception.
  TypeInitializationException
}

Object: GlobalResult (level 3)
{
  Can't find method:“Void UnitsNet.QuantityInfo`1..ctor(System.String, UnitsNet.UnitInfo`1<!0>[], !0, UnitsNet.IQuantity`1<!0>, UnitsNet.BaseDimensions, UnitsNet.QuantityType)”。
  MissingMethodException
}

Object: ReactionForce (level 1)
{
  Exception has been thrown by the target of an invocation.
  TargetInvocationException
}

Object: ReactionForce (level 2)
{
  The type initializer for 'Oasys.Units.Moment' threw an exception.
  TypeInitializationException
}

Object: ReactionForce (level 3)
{
  Can't find method:“Void UnitsNet.QuantityInfo`1..ctor(System.String, UnitsNet.UnitInfo`1<!0>[], !0, UnitsNet.IQuantity`1<!0>, UnitsNet.BaseDimensions, UnitsNet.QuantityType)”。
  MissingMethodException
}

Object: BeamForces (level 1)
{
  Exception has been thrown by the target of an invocation.
  TargetInvocationException
}

Object: BeamForces (level 2)
{
  The type initializer for 'Oasys.Units.Moment' threw an exception.
  TypeInitializationException
}

Object: BeamForces (level 3)
{
  Can't find method':“Void UnitsNet.QuantityInfo`1..ctor(System.String, UnitsNet.UnitInfo`1<!0>[], !0, UnitsNet.IQuantity`1<!0>, UnitsNet.BaseDimensions, UnitsNet.QuantityType)”。
  MissingMethodException
}

**Comment by kpne** [comment]
Hey @netsonicyxf , thank you for flagging this. We have solved it in the next version `0.9.22-beta`. You'll need GSA 10.1.60 or above to use the latest version of GsaGH.
