### ISSUE TITLE
How to create 3D elements without remeshing 3D member?

### ISSUE THREAD

**Issue by netsonicyxf** [arup-group/GSA-Grasshopper#138]
I have a mesh box with 2 faces in each X, Y and Z directions.
I want to get 3D elements with the same meshes as in the original mesh box. 
But the "Elements from Members" seems to remesh the 3D member.
![image](https://user-images.githubusercontent.com/43513391/181866347-c1450e81-1002-416c-97e9-3ff38025187e.png)
![image](https://user-images.githubusercontent.com/43513391/181866362-7e6f32d1-5e6b-425d-b715-6bf37d18f194.png)

**Comment by kpne** [comment]
Hi @netsonicyxf ,
The mesh size (`Ms` input) will determine the size and thus number of meshes that's created. If you just need two divisions you can set the mesh size to half the of your box edges.
Feel free to contact me at kristjan . nielsen at arup.com for faster reply.
Let me know if this solves your issue.
