### ISSUE TITLE
The GSA componnet takes time to show on the canvas

### ISSUE THREAD

**Issue by netsonicyxf** [arup-group/GSA-Grasshopper#139]
0.9.22 beta. When I put any GSA componnet on the canvas, it takes 5-6 sec to show.

**Comment by kpne** [comment]
Thanks for reporting this, we will look into it. 
Marked as GSAGH-90 for internal reference

**Comment by kpne** [comment]
@netsonicyxf  we believe this should be solved now with latest version 0.9.24. Do let us know if you are still facing issues after updating.
