### ISSUE TITLE
Object reference not set to an instance of an object - Cannot read GSA model

### ISSUE THREAD

**Issue by matteodini** [arup-group/GSA-Grasshopper#168]
Hello everybody

I build a model in GH, send it to GSA and try to read back. But I get this error:

**Solution exception:Object reference not set to an instance of an object.**

This problem does not occur defining a model from GSA and reading back with GH.

Thanks

Matteo

**Comment by kpne** [comment]
Ciao Matteo, 
Which component is giving you this error?
Can you share your file with us? SupportEmail - Oasys Structural Ecosystem <040a65ec.arup.onmicrosoft.com@emea.teams.ms>

**Comment by matteodini** [comment]
Hi Kristjan

Sharing the file is not possible I am afraid because it is a model under
NDA.
However here a screenshot of the error

[image: image.png]

As you can see only the nodes are imported

Could you help me?

Thank you

Matteo

Il giorno gio 29 set 2022 alle ore 14:57 Kristjan Nielsen <
***@***.***> ha scritto:

**Comment by kpne** [comment]
I cannot see the screenshot either I'm afraid.

Could you replicate the error you get with some simple geometry that is not under NDA?
Which component is throwing the error?
What version are you on?

**Comment by elenimcfarland** [comment]
Hello, 
I am having the same problem. 
- when i use the Get Geometry function, it only is bringing in the nodes. No data for any of the elements. 
- same thing for the Get Properties function, nothing is being brought in.
Attached is a screenshot of the two failing functionalities.
![Capture](https://user-images.githubusercontent.com/113617340/193149019-d9f9e327-68ee-4147-abc2-64aa50c3d3b5.JPG)

**Comment by matteodini** [comment]
Hi Kristjan

I did a simple example and the error persist

Attached the files


Il giorno gio 29 set 2022 alle ore 15:10 Kristjan Nielsen <
***@***.***> ha scritto:

**Comment by kpne** [comment]
Hi @matteodini,
Please try update to 0.9.29-beta and let me know if that solves the issue.

**Comment by matteodini** [comment]
I attached thescreenshot maybe now you can take a look

GetGeo-> import nodes but not 1D or 2D elements
GetProperties-> 1*. Solution exception:Object reference not set to an
instance of an object.*

GSA Grasshopper Plugin V 0.9.28-beta
API Version GSA 10.1 .NET API beta



Il giorno gio 29 set 2022 alle ore 15:10 Kristjan Nielsen <
***@***.***> ha scritto:
