### ISSUE TITLE
Version Availability Mismatch

### ISSUE THREAD

**Issue by jjsolly** [arup-group/GSA-Grasshopper#261]
Hi all

On the "Oasys Software Licensing Portal" where we can download updates to our software, the available version is only 10.1.62.90 

The latest GSA-Grasshopper requires 10.1.63. 

Can you kindly ask whoever manages the licencing portal to update.

**Comment by kpne** [comment]
Hi @jjsolly 
Apologies for that, there's an issue with SoftwareKey's Electronic Software Delivery (ESD) currently preventing us from uploading the latest version to the portal. I'll email you a direct link to 10.1.63. 
Best, Kristjan

**Comment by jjsolly** [comment]
Thanks Kristjan!
