### ISSUE TITLE
Why Element IDs are zeros?

### ISSUE THREAD

**Issue by netsonicyxf** [arup-group/GSA-Grasshopper#333]
![image](https://user-images.githubusercontent.com/43513391/221603261-a75d679f-9220-4076-8ab1-06f4843e3f93.png)

**Comment by kpne** [comment]
Hi @netsonicyxf, apologies for the late reply.

The IDs in all objects (Sections, Prop2d/3d, Nodes, Elements, Members, etc) works like this:
- If the hasn’t been part of an assembled model yet the ID will be zero
- After assembling the model the objects (coming out of the model with for instance GetGeometry component) will have been given an ID automatically by GSA
- You can set the ID to overwrite existing objects in a model
- Objects with ID = 0 will always be appended to the model.
