### ISSUE TITLE
Issue with recognizing load panel 2D elements

### ISSUE THREAD

**Issue by Marzalon** [arup-group/GSA-Grasshopper#351]
Hello team!

I've been using the GsaGH plugin with great pleasure. However, I ran into an issue when using the 2D element load panels.
When I create the panels and load them, it does not recognize the load panels correctly.
It creates them perfectly fine, but it seems to not automatically detect the load panel edges.
When I open the model in GSA, and go to the 2D property wizard, and simply click "Ok" through it, it does fix the issue.

Is this an issue on my end, or could it be that the GsaGH plugin does not correctly/fully initialize the load panels?

As the panels are not initialized correctly, I'm not able to directly access the results in GH which is a shame (also making optimization not possible sadly).

![2D](https://user-images.githubusercontent.com/1913556/227656254-e3ec1e8e-9bfc-4630-9d36-9a420d1ac225.jpg)
![LP](https://user-images.githubusercontent.com/1913556/227656505-ba68ee81-b49d-4910-9bb6-f3232aed168a.jpg)

**Comment by kpne** [comment]
Hi @Marzalon,
Thanks for the feedback. 

We are aware of this limitation and have already started working on a fix; 

The upcoming version 10.1.65 of GSA will include the ability to set support type of load panels through the API and we will soon after the release make that available in the Grasshopper plugin as well.

**Comment by Marzalon** [comment]
Thanks for the information!
Then I'll be awaiting the upcoming updates.
