### ISSUE TITLE
Can't rebuild the code due to error the type or namespace name 'SupportType' not exist

### ISSUE THREAD

**Issue by aleaperovskic** [arup-group/GSA-Grasshopper#386]
Hi, Dear,

I can't rebuild the code downloanded using Visual Studio 2022. The VS complaining that the class StructureType could not be found in any of the files in the project folder.

This error happen in CreateProp2d.cs and GsaProp2d.cs files.

Can suggestion? Do I need to download more dependencies or package before I can rebuild GsaGH in my own PC?

Thanks.

![Capture](https://user-images.githubusercontent.com/27995208/236096875-ff655dd4-0f03-439d-a2c8-961e3586d9d1.PNG)

**Comment by kpne** [comment]
Hi @aleaperovskic,
Unfortunately we found an issue with GSA version 10.1.65 - we pulled the version before it was released but unfortunately we had already merged new features of GsaGH to `main` before the issue was found. There’s therefore an intermediate issue for external people until we release GSA 10.1.66. This should happen within a few weeks I hope.

Best, Kristjan

**Comment by aleaperovskic** [comment]
> Hi @aleaperovskic, Unfortunately we found an issue with GSA version 10.1.65 - we pulled the version before it was released but unfortunately we had already merged new features of GsaGH to `main` before the issue was found. There’s therefore an intermediate issue for external people until we release GSA 10.1.66. This should happen within a few weeks I hope.
> 
> Best, Kristjan

Hi, kristjan, thanks for the reply. My intial guess is that there have some conflict between the class definition of the GsaAPI.dll and the GsaGH file desciption, e.g. class Prop2D.SupportType. That might the reason why external people like me encounter error during trying to rebuliding the GsaGH in Visual Studio.
Best,
JL

**Comment by kpne** [comment]
You can, for now as a work around, revert GsaProp2d and related files to their previous versions or simply comment out the references to SupportType.

**Comment by kpne** [comment]
Version of GSA resolving this will be released next week.
