### ISSUE TITLE
Why there is an error in the Element From Member?

### ISSUE THREAD

**Issue by netsonicyxf** [arup-group/GSA-Grasshopper#655]
How to resolve it?
![image](https://github.com/arup-group/GSA-Grasshopper/assets/43513391/62a0ba5b-9946-43c2-a04d-1f133f600498)
[3D elements.zip](https://github.com/arup-group/GSA-Grasshopper/files/14773501/3D.elements.zip)

**Comment by tlmnrnhrdt** [comment]
@netsonicyxf What is the error message?

**Comment by tlmnrnhrdt** [comment]
Your mesh size seems to be smaller than your tolerance, if I change that it works for me on Rhino 7

![Untitled](https://github.com/arup-group/GSA-Grasshopper/assets/45289620/7fc4f0fe-89fd-47f3-bf01-b797b2c6097d)
