### ISSUE TITLE
Gsa 2d Member remesher  issue

### ISSUE THREAD

**Issue by Marco-Pellegrino** [arup-group/GSA-Grasshopper#87]
Hi @kpne !

I have tried to use **Elem2dFromBrep** and, sometimes, I have notice a weird behaviour as shwon in the picture below.
Are you aware of it?

![image](https://user-images.githubusercontent.com/53620289/134707044-6531855c-c257-4927-8e1f-6385e89a5b92.png)

**Comment by kpne** [comment]
Hi Marco,
Yes, there is a known issue with the Elem2dFromBrep when trying to unfold surfaces of high curvature. You can split into smaller pieces and re-mesh each piece individually, you can use the naked vertices as inclusion points for the next piece to get it all lined up neatly. 
Send me a file if you are having issues, happy to help - kristjan . nielsen <at> arup . com
Best, Kristjan
