### ISSUE TITLE
GSA 0.35 can't be loaded

### ISSUE THREAD

**Issue by netsonicyxf** [arup-group/GSA-Grasshopper#89]
I get 0.35 through RH6.34 packagemanager.
After relaunch the RH, it shows 

GSA: GsaAPI.dll loading
Error: HRESULT:0x80070002)

This may be due to clash with other referenced dll files by one of these plugins that's already been loaded: 
-Grasshopper-Tekla Link 2021.1.9
-LunchBox
-LunchBoxML
-Pangolin
-ProvingGround.ConveyorGHV6
-EleFront
-Hare
-Human
-MetaHopper
-Pancake
-Vipers
-KarambaIDEA
-Koala
-Test
-NExcel
-Opossum2_0_Proto_A
-Panda
-Panda
-pOd_GH_Button
-pOd_Animation
-pOd
-SemanticV6GH
-Swallow(ESD)
-sof_gh_axis_modeling-2022
-sof_gh_sofistik-2022
-BullAnt
-GrasshopperRfem5ComComponent

You may try disable the above plugins to solve the issue.
The plugin cannot be loaded.
{Exception}

**Comment by kpne** [comment]
Hi @netsonicyxf,
The HRESULT:0x80070002 error is a 'File not found' error, which indicates you may not have GSA installed. Can you confirm that you have GSA10.1 installed, and that you have a file named 'GsaAPI.dll' located in C:\Program Files\Oasys\GSA 10.1?

If yes, this may be an error with conflicting dll's as explained by the error message you receive (and you have pasted above). One of your installed plugins may be referencing a dll with the same name as one that GSA is also using in the background, but with different versions. We have seen this error with old version of Karamba running on Rhino6, you can try either uninstall Karamba or upgrade to Rhino7 to see if that solves the issue.
