### ISSUE TITLE
Request: Load Combination result

### ISSUE THREAD

**Issue by Marco-Pellegrino** [arup-group/GSA-Grasshopper#93]
Hi @kpne 

is there a way to read the Load Combination results with your tool?
I am able to read the Load Case results but It would be great to get the Load Combination as well.

Thanks,
Marco

**Comment by kpne** [comment]
Hi Marco,
It has just been added to the GsaAPI and will be included in the next release of GsaGH.

**Comment by kpne** [comment]
Hi @Marco-Pellegrino, creating load combinations and getting results from these are now available through the plugin.

**Comment by Marco-Pellegrino** [comment]
Perfect!
Well done
