### ISSUE TITLE
NodeEdit - Variable parameter methods not implemented

### ISSUE THREAD

**Issue by DominicBeer** [arup-group/GSA-Grasshopper#94]
Had the NodeEdit component throwing exceptions on me when using the plugin - found this bug thought I would let you know

https://github.com/arup-group/GSA-Grasshopper/blob/05b5f1396e44314be1bd8e61754f05ab6df816f9/GhSA/Components/2_Geometry/EditNode.cs#L268-L286

**Comment by kpne** [comment]
Hey @DominicBeer, thanks for flagging this and apologies for not reacting before - we had completely missed this. It has been solved now, thanks again!
